name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: martinyg
        DOCKER_PASSWORD: EARTHcolor908
      run:
        docker login -u martinyg -p EARTHcolor908
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Docker Push
      run: docker push martinyg/cloudcomputing-lab02
